import './menu.js';
import './header.js';
import './search.js';
import './header-dropdown.js';
import './filter-dropdown.js';
import './input-state.js';
import './account-modal.js';
import './fit-images.js';
import './step-carousel.js';
import './product-carousel.js';
import './range-slider.js';
import './accordion.js';
import './add-ingredients.js';
import './detect-safari.js';
// import './dosage.js';
